---
title: "Advanced Informatics HW2"
output: html_document
---
## First, let's do it in R

```{r}
mycurrentdirectory = dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(mycurrentdirectory)
library(dbplyr)
library(dplyr)
library(RSQLite)
library(printr)

data(mtcars)
help(mtcars)
head(mtcars)
```

```{r}
aggregate(mpg ~ cyl, data=mtcars, mean)
aggregate(mpg ~ cyl + gear, data=mtcars, mean)

results = mtcars %>%
  group_by(cyl) %>%
  summarise(mean_mpg = mean(mpg))
results
results = mtcars %>%
  group_by(cyl, gear) %>%
  summarise(mean_mpg = mean(mpg))

## `summarise()` regrouping output by 'cyl' (override with `.groups` argument)

as.data.frame(results)


```

```{r}
con <- DBI::dbConnect(RSQLite::SQLite(), "mtcars.sqlite3")
DBI::dbWriteTable(con, "mtcars", mtcars)
DBI::dbDisconnect(con)

list.files(path = mycurrentdirectory, "mtcars.sqlite3")

con <- DBI::dbConnect(RSQLite::SQLite(), "mtcars.sqlite3")
mtcars2 <- tbl(con, "mtcars")
g = mtcars2 %>% 
  group_by(cyl) %>%
  summarise(mean_mpg=mean(mpg))

g %>% show_query()

result = g %>% collect()
as.data.frame(result)
```

## Now, let's do it in Python!!!

```{r reticulate, include=FALSE}
library(reticulate)
knitr::opts_chunk$set(echo = TRUE)
```

```{python}
mtcars = r.mtcars
mtcars.head()
```

```{python}
import pandas
mtcars.groupby(['cyl'])['mpg'].mean()
mtcars.groupby(['cyl', 'gear'])['mpg'].mean()
```

```{python}
import sqlite3 # Built into the Python language!
con = sqlite3.connect("mtcars_from_pandas.sqlite3")
# Add our data frame to the mtcars table in the database
mtcars.to_sql("mtcars", con)
con.close()

from os import listdir
listdir()
```

```{python}
import pandas as pd
con = sqlite3.connect("mtcars_from_pandas.sqlite3")
df = pd.read_sql("select * from mtcars", con)
df.head()
```

```{python}
df = pd.read_sql("select cyl, avg(mpg) from mtcars group by cyl", con)
df.head()
df = pd.read_sql("select cyl, gear, avg(mpg) from mtcars group by cyl, gear", con)
df.head()

```